# Gene Ontology Semnatic Similarity.R
# Calculate pairwise Gene Ontology semantic similarity score based on Schlicker's method
# V 0.4
# Wilfred de Vega, April 8, 2015
#
# Semantic similarity scores, based on Schlicker's method, are calculated based on
# Cellular Component and Biological Pathway Gene Ontology terms. This track requires
# a list of genes and determine pairwise scores. The average of the two scores will be
# calculated and gene pairs with a score higher than 0.2 will be in the final output.
#
# Input:      List of Genes
# Output:     Average pairwise semantic similarity scores higher than 0.2
# Parameters: Entrez IDs are required for the genes and a Gene Ontology must exist for
# the species of interest.
#
# Notes:
# Update (April 8, 2015): Added some code to deal with blank and multiple Entrez ID entries
# considering the output generated by Peter's List of Genes track. Also added statements to 
# make the code seem more responsive (confirming that the code is actually calculating values
# rather than remaining silent).
#
# Issues / ToDo:
# Determine a more efficient way to calculate scores (currently, this track will process
# a list of 100 genes in 6 minutes with 8GB RAM).
#
# =====================

LoGtable <- read.table("Genome - GeneID, BioCycID, GeneSymbol.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE) #from List of Genes

# Load the GOSemSim library, or download it if not available.
# Will also download the 27.5 Mb dependency "GO.db" if not available
if (! require(GOSemSim)) {
	source("http://bioconductor.org/biocLite.R")
	biocLite("GOSemSim")
}

# Load pbapply package or download it if not available (adds progress bar to apply function).
if (! require(pbapply)) {
  install.packages("pbapply")
}

entrezID <- LoGtable[,"Gene.ID"] #obtain EntrezIDs from List of Genes table
blank.ind <- which(entrezID == "-") #which indices do not have an Entrez ID
if(length(blank.ind != 0)){ #if there are blank Entrez IDs
  entrezID <- entrezID[-blank.ind] #remove all blank Entrez ID indices
}

if(length(grep("; ", entrezID) != 0)) { #if the list contains multiple Entrez IDs for a gene
  entrezID <- unlist(strsplit(entrezID, "; ")) #generate a character vector with all Entrez IDs (including those with multiple entries)
}

genecombo <- t(combn(entrezID, m = 2)) #obtain every possible combination of 2 genes. Transpose the matrix to make it easier to read.
colnames(genecombo)[1:2] <- c("GeneA", "GeneB") #Rename the first two columns for clarity

print("Now calculating Cellular Component Semantic Similarity Scores...")
CCscore <- pbapply(genecombo, 1, function(x){ #Calculate CC GO Semantic Similarity Scores over each row (1) of the matrix
  CCSemSim <- geneSim(x[1], x[2], ont = "CC", organism = "human", measure = "Rel", combine = "BMA") #should return a vector of 3 elements
  if(length(CCSemSim) < 3){ #if a vector of a length < 3 is returned (ie. calculation fails due to lack of GO annotations)
    CC <- 0 #assign a CC score of 0
  }
  else{
    CC <- CCSemSim$geneSim #The data is organized as a vector with 3 elements so we must extract the scores this way
  }
  if(is.na(CC)){
    CC <- 0 #If the score is NA, assign a score of 0
  }
  else{
    CC <- CC
  }})

print("Now calculating Biological Process Semantic Similarity Scores...")
BPscore <- pbapply(genecombo, 1, function(x){ #Calculate BP GO Semantic Similarity Scores over each row (1) of the matrix
  BPSemSim <- geneSim(x[1], x[2], ont = "BP", organism = "human", measure = "Rel", combine = "BMA")
  if(length(BPSemSim) < 3){ #if a vector of a length < 3 is returned (ie. calculation fails due to lack of GO annotations)
    BP <- 0 #assign a BP score of 0
  }
  else{
    BP <- BPSemSim$geneSim
  }
  if(is.na(BP)){
    BP <- 0 #if BP score is NA, assign a BP score of 0
  }
  else{
    BP <- BP
  }})

print("Producing final GOSem Output...")
RawScores <- cbind(CCscore, BPscore) #combine raw scores into table
GOSEMScore <- rowMeans(RawScores) #calculate average of raw GO Semantic Similarity Score
TOTALGOSEM <- cbind(genecombo, GOSEMScore) #compile table with all gene pairs and GOSEMScores
passthresh <- which(TOTALGOSEM[,"GOSEMScore"] > 0.2) #determines indices of the table (gene pairs) that pass the 0.2 threshold
GOSemSim <- TOTALGOSEM[passthresh,] #produce a table with gene pairs that pass GO Semantic Similarity threshold
print("GOSem Track Complete!")